kind: Service
apiVersion: v1
metadata:
.  name: busilopreact
  labels:
    app: node
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busilopreact
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "busilopreact"
        dapr.io/port: "80"
    spec:
      containers:
        - name: node
          image: dapriosamples/hello-k8s-node:edge
          ports:
            - containerPort: 80
          imagePullPolicy: Always
